from typing import Any, Callable, NoReturn

from flask import Flask

def emit(event: str, *args: Any, **kwargs: Any) -> None: ...

class ThreadLike:
    def join(self) -> None: ...

class SocketIO:
    def __init__(self, app: Flask = None, **kwargs: Any) -> None: ...
    def run(self, app: Flask, host: str = None, port: int = None, **kwargs: Any) -> NoReturn: ...
    def emit(self, event: str, *args: Any, **kwargs: Any) -> None: ...
    def event(self, *args: Any, **kwargs: Any) -> Any: ...
    def start_background_task(
        self, target: Callable[..., Any], *args: Any, **kwargs: Any
    ) -> ThreadLike: ...
    def sleep(self, seconds: float = 0) -> None: ...
